### ISSUE TITLE
installation instructions

### ISSUE THREAD

**Issue by auzadventure** [digicomsujan/review_material#1]
What's the installation instructions? 

home page is empty?
-what's the path to run the code from the index page? 

- Summary of what the application is.

**Comment by digicomsujan** [comment]
Sorry for the late reply. The installation process is simple extract it and import the database. Change in 
application/config/config.php -> base_url
also change the database information in database.php
and run the url:- http://localhost/codeigniter/ci_attendance/index.php/attendance/index_bkup
it does not have any design since i just took the main function that does all the things.

the summary for this application is that I get data in devicelog table. and have to process it and save it in attendance table.
